import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from jack" });

  return (
    <>
      <Head>
        <title>Digio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to <span className="text-[hsl(280,100%,70%)]">Digio</span>
          </h1>
          {/* <button className="text-2xl bg-[#6D59FF] text-white py-2 px-6 rounded-full">Connect Wallet</button> */}
          <Link href={"/sell"}>
            <button className="text-2xl bg-white text-[#6D59FF] py-2 px-6 rounded-full">
              Sell on Digio
            </button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
